### ISSUE TITLE
How to set a dynamic image version?

### ISSUE THREAD

**Issue by apeschel** [CircleCI-Public/docker-orb#10]
### Orb version

0.5.3

### What happened

We would like to be able to use dynamic versioning for our docker images, but we seem to only be able to set static tag values for the docker image.

Is it possible to set a dynamic version akin to something like this?

```
      - docker/publish:
          tag: $(./version.sh)
```

**Comment by iynere** [comment]
@apeschel not right out of the box, as the config will be interpolated right at runtime, before your shell script has a chance to run.

however, you should be able to parameterize the tag value on the pipeline level and use the new V2 api to trigger a pipeline that will run the `docker/publish` job with a dynamically determined pipeline parameter value:

https://github.com/CircleCI-Public/api-preview-docs

this V2 api functionality is brand new, so we will likely be rolling out a bunch of new orb functionality to take advantage of it, but for the timebeing, you will have to figure it out for yourself using the API documentation. feel free to post a general form of this question on Discuss, as well—it's possible other users who are experimenting with the V2 api have figured out the flow for this type of thing already:

https://discuss.circleci.com/c/environment

**Comment by bzon** [comment]
@iynere how about adding a simple if-else command right before the `docker push` command? We know that in CircleCI, environment variables can be manipulated within the job scope using a `BASH_ENV` hack.

```yaml
steps:
  - deploy:
      name: <<parameters.step-name>>
      command: |
        IMAGE_TAG=${CUSTOM_IMAGE_TAG:-<< parameters.tag >>}
        docker push <<parameters.registry>>/<< parameters.image>>:${CUSTOM_IMAGE_TAG}
```

or maybe add a **get_image_version_script** parameter..


```yaml
steps:
  - deploy:
      name: <<parameters.step-name>>
      command: |
        IMAGE_TAG=<< parameters.tag >>
        if [[ -f << parameters.get_image_version_script >> ]]; then
            IMAGE_TAG=$(bash << parameters.get_image_version_script >>)
        fi
        docker push <<parameters.registry>>/<< parameters.image>>:${IMAGE_TAG}
```

Source: https://github.com/CircleCI-Public/docker-orb/blob/68825df4f93e87ac74e45b886ce25f023332a0ed/src/commands/push.yml#L24-L28
