### ISSUE TITLE
Feature request: Changelog

### ISSUE THREAD

**Issue by caleb15** [CircleCI-Public/docker-orb#103]
I see that the orb was upgraded to v2, which as per semver indicates possibly breaking changes, but I'm not sure what the changes are. It would be great if there was a changelog so I could easily see the changes being made.

**Comment by EricRibeiro** [comment]
Hi, @caleb15 👋 

When the Docker Orb gets migrated to Orb Tools 11 in #108, future releases will come with changelog such as this one: https://github.com/CircleCI-Public/slack-orb/releases/tag/v4.9.4
