### ISSUE TITLE
`install-docker-compose` doesn't clean up after itself

### ISSUE THREAD

**Issue by ben-page** [CircleCI-Public/docker-orb#133]
### Orb version

2.1.1
### What happened
Ran `install-docker-compose` and it left `docker-compose-linux-x86_64.sha256` behind.

### Expected behavior
`install-docker-compose` (and others) should delete any files downloaded to the working directory.

**Comment by iggy** [comment]
Yeah, this causes a checkout that runs after this step to fail because the workdir isn't empty.
