### ISSUE TITLE
Login using --password-stdin

### ISSUE THREAD

**Issue by tuler** [CircleCI-Public/docker-orb#14]
https://github.com/CircleCI-Public/docker-orb/blob/38109f0ba6ab2f95bf8b64a27bddd2f516756553/src/commands/check.yml#L34

Docker says:
`WARNING! Using --password via the CLI is insecure. Use --password-stdin.`

This should be replace by:

```
        echo "$<<parameters.docker-password>>" | docker login \
          -u "$<<parameters.docker-username>>" --password-stdin \
          <<parameters.registry>>
```

**Comment by filalex77** [comment]
Bookmarked.

**Comment by piyush-insider** [comment]
Hi @tuler @filalex77 Is it all right if I work on this?

**Comment by filalex77** [comment]
@piyush-insider Sure, you're welcome - I'm still a bit busy. Good luck!

**Comment by piyush-insider** [comment]
Thanks @filalex77 Will get the PR ready!
