### ISSUE TITLE
Unable to install version 2.10.0 of docker-compose

### ISSUE THREAD

**Issue by jlambert121** [CircleCI-Public/docker-orb#140]
### Orb version

2.1.2

### What happened

Fetching the latest version of `docker-compose` fails due to the changes in the release files generated by the compose project - version `2.10.0` no longer generate the `sha256` files.

### Expected behavior

Installing `docker-compose` without specifying a version should install the latest version.

**Comment by iggy** [comment]
We're hitting this too. Adding `docker-compose-version: 2.9.0` everywhere that installs docker tools is going to be painful.
