### ISSUE TITLE
Impossible to use an environment variable for the `registry` parameter in `docker/push`

### ISSUE THREAD

**Issue by Grmiade** [CircleCI-Public/docker-orb#151]
### Orb version

circleci/docker@2.1.3

### What happened

We encounter this error `invalid reference format: repository name must be lowercase` with the command `docker/push`. Probably because we use an environment variable for the `registry` parameter.

### Expected behavior

We should be able to use an environment variable for the `registry` parameter.
It works with `circleci/docker@2.1.1`.

**Comment by rayterrill** [comment]
Just ran into this as well. @EricRibeiro looks like https://github.com/CircleCI-Public/docker-orb/commit/b0806e1bbb9c8c5b55e2e9eaccc569c8bdc9493d added a check.sh.

Should:
```
--password-stdin "$PARAM_REGISTRY"
```

Be?:
```
--password-stdin "${!PARAM_REGISTRY}"
```

Looks like this is using parameter indirection?

**Comment by Jrc356** [comment]
Looks like this is still an issue with 2.1.4 I suspect it has to do with not using `eval echo` similar to how `image` and `tag` work. I am using an env var for both `registry` and `tag` and it appears that `tag` expands properly but `registry` does not. `tag` is set via `eval echo` [here](https://github.com/CircleCI-Public/docker-orb/blob/014287b19d477ef7229cadf29886d1c64995aa4a/src/scripts/push.sh#L7-L8). I'll throw up a PR to do the same for registry

**Comment by cdhunt** [comment]
#111 Changed the registry value from being a parameter to an environment variable.

https://github.com/CircleCI-Public/docker-orb/commit/b0806e1bbb9c8c5b55e2e9eaccc569c8bdc9493d#diff-6a6efd15dcd99e5f9b7bb746e098e0bea169a2f954d044dcb7d28a05e6478c1e

This is a breaking change but only incremented as a minor release. It's not a refactor if you change/break existing functionality.
