### ISSUE TITLE
docker-credential-pass fails to download

### ISSUE THREAD

**Issue by ntse** [CircleCI-Public/docker-orb#154]
### Orb version

2.0.3

### What happened

The [DOWNLOAD_URL](https://github.com/CircleCI-Public/docker-orb/blob/69fc0902686343a3bd14b2367e1dcb759cd92941/src/scripts/install-docker-credential-helper.sh#L62) is no longer valid for docker-credential-pass as it is now released as a binary at https://github.com/docker/docker-credential-helpers/releases/download/${RELEASE_VERSION}/${HELPER_FILENAME}-${RELEASE_VERSION}.(linux/darwin)-amd64 instead of being an archive at https://github.com/docker/docker-credential-helpers/releases/download/${RELEASE_VERSION}/${HELPER_FILENAME}-${RELEASE_VERSION}-amd64.tar.gz

  
### Expected behavior

docker-credential-helpers should be downloaded.

**Comment by EricRibeiro** [comment]
Hi @ntse 👋 

Thank you for opening this issue. I'll look into it!

**Comment by EricRibeiro** [comment]
Fix release in [v2.1.4](https://circleci.com/developer/orbs/orb/circleci/docker?version=2.1.4).
