### ISSUE TITLE
docker-credential-helpers update issue with release 7.0

### ISSUE THREAD

**Issue by rit001** [CircleCI-Public/docker-orb#158]
An issue is being reported on the Circleci forum due to changes to docker-credential-helpers

https://discuss.circleci.com/t/circleci-docker-orb-docker-credential-helper-failing/45513

**Comment by brivu** [comment]
Hey @rit001, 

Thanks for opening this issue. It looks like this has been resolved already [with the current version](https://github.com/CircleCI-Public/docker-orb/blob/44f62951b0951e9765dc90e9355a00990170199b/src/scripts/install-docker-credential-helper.sh#L71-L87) of the orb. 

I'm going to go ahead and close this issue. 

Best, 
Brian
