### ISSUE TITLE
Does not work on ARM machines

### ISSUE THREAD

**Issue by alexeyshockov** [CircleCI-Public/docker-orb#160]
### Orb version

`circleci/docker@2.1.4`

### What happened

`docker/install-docker` ends up with

```
...
Latest stable version of Docker is v20.10.18
A different version of Docker is installed (Docker version 20.10.17, build 100c701); removing it
/bin/bash: line 75: /usr/local/bin/docker: cannot execute binary file: Exec format error
 has been installed to /usr/local/bin/docker
```

### Expected behavior

Fresh Docker is installed and _functional_.

**Comment by brivu** [comment]
Hey @alexeyshockov, 

I've noticed that you're using `circleci/docker@2.1.4` of the orb. If you update the version to `2.2.0`, the issue you're running into will be resolved. Just be sure to import the `docker-orb` in your config like below: 

```
version: 2.1

orbs:
  docker: circleci/docker@2.2.0
```

I'm going to close this issue for now. Please feel free to reopen if you still have issues. 

Thanks! 
Brian
