### ISSUE TITLE
Hadolint command expects Hadolint to be installed locally, doesn't use Docker image

### ISSUE THREAD

**Issue by hbielenia** [CircleCI-Public/docker-orb#170]
### Orb version
2.1.4

### What happened
Upon trying to run the `hadolint` command, I'm getting following error:
```
Running hadolint with the following options...


/bin/bash: line 24: hadolint: command not found

Exited with code exit status 127
```
Apparently, the command expects `hadolint` to be installed locally and available as executable, despite the [description](https://github.com/CircleCI-Public/docker-orb/blob/83e2896b6cfc942c77e7828b5224123a7c512353/src/commands/hadolint.yml#L1) clearly stating that it's `using a hadolint Docker image: https://hub.docker.com/r/hadolint/hadolint`.

### Expected behavior
Hadolint should be pulled from Docker repository and executed in Docker container, with no need to install additional dependencies.

**Comment by brivu** [comment]
Hey @hbielenia, 

Thank you for letting us know. You have a couple of options here: 

1.  You can use the `hadolint` docker image in your job to run this command.
2. You can just use the `hadolint` job. 

Having said that, I've added validation to this command to check and see if `hadolint` is installed. If not, the command will now install `hadolint` for you. 

I've added this in PR #175. 

Hope that helps!
