### ISSUE TITLE
Issues with image build in 2.5 orb

### ISSUE THREAD

**Issue by srinath92** [CircleCI-Public/docker-orb#193]
### Orb version
2.5.0

### What happened
We use this orb via gcp-gcr@0.16.3
The issue I see is with the build arguments passed to the build command and there by to build.sh.
Following is one of our jobs
`

docker_build_and_push_image:
 name: docker_build_and_push_image_test
          requires:
            - init
          service_id: test-service-id
          dockerfile: docker/php/containers/php-cron/Dockerfile
          image: test
          extra_build_args: --build-arg=IMAGE_NAME=test --build-arg=CRON_COMMAND='/usr/local/bin/php /app/bin/console business:abc:xyz'
          tag: latest
          context:
            - artifactory
`
So, if you look at the extra_build_args: arg in the above, it has an arg that is actually a command I need to be part of the image. But when trying to build the image via circle ci, I get the below error.

**ERROR: "docker buildx build" requires exactly 1 argument.
See 'docker buildx build --help'.

Usage:  docker buildx build [OPTIONS] PATH | URL | -

Start a build

Exited with code exit status 1**

When investigated a bit more, it looks like the shell interpreter is splitting the argument into something like `--build-arg=CRON_COMMAND='/usr/local/bin/php' /app/bin/console 'business:abc:xyz'`

We need to upgrade the orb version as circle ci is looking to remove the deprecated images.

### Expected behavior

The image should be built with the args passed above, as it used to be when using docker-orb@1.5

**Comment by srinath92** [comment]
This seems to be happening due to the quotes missing here https://github.com/CircleCI-Public/docker-orb/blob/354aaf5c4e483a9e0632fbd1ea0ab5ade1ee6701/src/scripts/build.sh#L77

**Comment by marboledacci** [comment]
The new version of docker orb was integrated in [version 0.16.4](https://circleci.com/developer/orbs/orb/circleci/gcp-gcr?version=0.16.4#orb-source) of the gcp-gcr orb. 
I will close this.
