### ISSUE TITLE
Removal of use-buildkit key causes builds with --secret env setting to fail

### ISSUE THREAD

**Issue by AndrewGearhart** [CircleCI-Public/docker-orb#197]
### Orb version

2.7.1

### What happened

Using:
```
    - docker/build:
        extra_build_args: "--secret id=COMPOSER_AUTH,env=COMPOSER_AUTH"
```
Results in:
```
+ docker buildx build --file=./Dockerfile --tag=imagename:imagetag --secret=id=COMPOSER_AUTH,env=COMPOSER_AUTH .
error: unexpected key 'env' in 'env=COMPOSER_AUTH'

Exited with code exit status 1
```
### Expected behavior

The build should be properly understanding the environment variable name that is passed to it through the extra_build_args ... however, it isn't. 
Variants that have been tried include:
`--secret=id=COMPOSER_AUTH,env=COMPOSER_AUTH`
and
`--secret id=COMPOSER_AUTH,env=COMPOSER_AUTH`

Both seem to dislike the explicit env setting for the secret arg... This has happened previously when the build isn't using a recent dockerfile syntax interpreter which is set in the Dockerfile with `#syntax=docker/dockerfile:1`

Note that this worked properly in 2.6.0. My read is that it probably comes from the removal of the option to use buildkit here:
https://github.com/CircleCI-Public/docker-orb/compare/v2.6.0...v2.7.1#diff-90233ceba51b90d3e1df993996cf7c68d7b560c9c2858415d311a21671c45bd3L110-L113

**Comment by marboledacci** [comment]
Hi @AndrewGearhart I'm taking a look at this. Where you using the `use-buildkit` parameter in version 2.6.0? If you were not I don't think this is related to that change, as the default for this is false.

**Comment by marboledacci** [comment]
@AndrewGearhart I have been doing some tests for this, using the `DOCKER_BUILDKIT=1` and not using it. With = and with space in the `--secret` flag, with `#syntax=docker/dockerfile:1` and without it. All of them have worked.

Could you give me more details about your Dockerfile and the environment you are using? That way I can replicate this better and come up with a solution.

**Comment by AndrewGearhart** [comment]
Hi there @marboledacci ! More than happy to provide any/all information I can.
I created a simple gist (it's secret, I know this reveals it, but I specifically anonymized it for this) here:
https://gist.github.com/AndrewGearhart/6c112f14ad1433dcbe8ff977a4a552ac

with 2.6.0, it works. with 2.7.1, it does not, failing with:
```
+ docker buildx build --file=./Dockerfile --tag=docker.io/library/composer-ci-testing:fc6c50127418d90b1ed7ef8f23d90e391b8a4f5f --secret id=COMPOSER_AUTH,env=COMPOSER_AUTH .
error: unexpected key 'env' in 'env=COMPOSER_AUTH'

Exited with code exit status 1
```

**Comment by marboledacci** [comment]
Thanks for sharing! It was very useful. 
I think the problem here is the executor. You are using the default docker executor of the orb, which works with cimg/python:3.6. I'm not sure what is the exact problem with that image and the newer version of the orb, but it is a really old image, so may be a difference in bash versions.

I tried other different executors, both docker and machine, and all of them worked fine.
I will update the default version for that executor in the next release as the current one is very old, but for now you can update it in your workflow just changing `executor: docker/docker` for:
```
executor:
      name: docker/docker
      tag: "3.8"
```
You can also use any other executor, this is just the most similar to what you already have.

**Comment by AndrewGearhart** [comment]
I can confirm that adding the tag to the executor also fixes this. Thanks for that tip! i'll be reading up more on orbs and executors next week. Looks like a fascinating way of handling things.
