### ISSUE TITLE
dockerlint is non-functional as described

### ISSUE THREAD

**Issue by jeff-knurek** [CircleCI-Public/docker-orb#40]
### Orb version

0.5.17

### What happened

PR #12 removed the documentation about requiring NPM, but the step of `dockerlint` command still attempts to install dockerlint as an npm package, and NOT hadolint as described/documented

### Expected behavior

I expected the `dockerlint` command to work using hadolint as described.

## Additional

It looks to me like nobody even approved/reviewed PR #12. Am I right? If so, this isn't the kind of development quality we should be expecting from "certified" orbs.

**Comment by iynere** [comment]
@jeff-knurek dockerlint & hadolint are 2 separate tools

`hadolint` is available as a job, `dockerlint` is available as a command

the `hadolint` job uses hadolint, the `dockerlint` command uses dockerlint

they are available this way b/c of how these tools are distributed—e.g., hadolint provides a docker image, so the easiest way to use it is by spinning up a job using that docker image. whereas dockerlint is more easily installed as a CLI tool.

can you post the specific error messages you're seeing ? trying to combine them (if that's what you're doing) will definitely not work & is not intended to. but perhaps there's some documentation we could write to clarify this ?

**Comment by jeff-knurek** [comment]
https://github.com/CircleCI-Public/docker-orb/pull/12/files#diff-f1d93cdf2308874e6eac36caba1eea1eR9

The PR referenced clearly made an attempt to change the `dockerlint` command, but instead of actually improving it, just confused  the documentation instead.  

----
My personal request, is that if you are going to keep `dockerlint` using the npm package, that you also move the logic of the `hadolint` job into a command that can be reused 

----
I'm also a little upset that you failed to acknowledge the most alarming thing about this issue: 
> It looks to me like nobody even approved/reviewed PR #12. Am I right? If so, this isn't the kind of development quality we should be expecting from "certified" orbs.

**Comment by iynere** [comment]
> The PR referenced ... just confused the documentation

🤦🏼‍♀️ i'm sorry, don't know how i missed this—had recently returned from a very long leave last week. yes, the dockerlint command has the WRONG (not just confusing) documentation—will fix asap, thank you.

> My personal request, is that if you are going to keep dockerlint using the npm package, that you also move the logic of the hadolint job into a command that can be reused

`hadolint` works better as a job than a command, for the reasons i outlined previously (e.g., it is most easily/reliably used, as recommended by its developers, by spinning up their 1st-party docker image, which in turn clearly maps most easily/directly onto a circleci job, as opposed to a command). however, we can likely add an additional `hadolint` command, which will have to first install (in a different, possibly less simple / reliable manner), and then use, `hadolint` within any given circleci job.

> It looks to me like nobody even approved/reviewed PR #12. Am I right? If so, this isn't the kind of development quality we should be expecting from "certified" orbs.

true, as a repo administrator, i wrote the code in those commits, opened the PR, & merged it without review, which is certainly not a best practice for us... in july, Community/Partner Engineering was a team of 2. we are now larger 🎉& so this type of occurrence is less common.

thank you for your valuable, & persistent, feedback! will @ you on the PR to address what you've brought up here

**Comment by iynere** [comment]
@jeff-knurek since the documentation for the `dockerlint` command has been fixed (https://github.com/CircleCI-Public/docker-orb/releases/tag/v0.5.19), i'm going to close this issue in favor of https://github.com/CircleCI-Public/docker-orb/issues/42, which will focus on adding a `hadolint` command. thank you !
