### ISSUE TITLE
Add `hadolint` as a command

### ISSUE THREAD

**Issue by iynere** [CircleCI-Public/docker-orb#42]
`hadolint` is available as a job, but not an isolated command, as noted in https://github.com/CircleCI-Public/docker-orb/issues/40

**Comment by SEdilson** [comment]
Is anyone getting this? I'd like to get it.

**Comment by dsayling** [comment]
please feel free and submit a PR

**Comment by gmemstr** [comment]
Taking a look at this today. Does strike me as slightly odd that this is only available as a job.
