### ISSUE TITLE
fail version check when you run docker/install-docker-compose

### ISSUE THREAD

**Issue by Pegasus204** [CircleCI-Public/docker-orb#49]
### Orb version

`v0.5.20`

### What happened

docker-compose version naming conversion has changed to `vX.Y.Z` from `X.Y.Z`.
when you run [this command](https://github.com/CircleCI-Public/docker-orb/blob/86328bde8360ba6c4c4cd0458c3dc3b8353d4f38/src/commands/install-docker-compose.yml#L58) circleci compares `v1.25.2` and `1.25.2`. Then failed.

### Expected behavior

I expect to this orb to be able to compare correct docker-compose version.

**Comment by Pegasus204** [comment]
It seems docker-compose will release new one without ‘v’ in release tag.
ref.) https://github.com/docker/compose/issues/7168

If you fail installing docker-compose due to unmatched version check, you can resolve this error by add docker-compose version <= 1.25.1 following like this.

```yaml
steps:
  - docker/install-docker-compose:
      version: "1.25.1"
```

So, I closed my Pull-Request.

**Comment by KyleTryon** [comment]
Thanks @Pegasus204,

We appreciate you bringing it up and submitting a PR! Looks like as you have pointed out that Docker has resolved this by including a release without the `v` 🎉 .

Thank you again!
