### ISSUE TITLE
Realistic example - please?

### ISSUE THREAD

**Issue by otobrglez** [CircleCI-Public/docker-orb#5]
Hello! 👋 

I've started experimenting with CircleCI's Docker ORBs - specifically with `circleci/docker@0.5.0` and I was wondering if there is a way to show audience and your customers some realistic examples on how to mix this orb with other orbs and how to use this orb after the docker image was built? I.e. docker image is built, now how to properly run it? (not with `after_build:` hook - obviously. )

Thanks for your feedback and thanks for pushing this!

Regards,

- Oto

**Comment by iynere** [comment]
@otobrglez this orb doesn't currently provide any `docker run` functionality—typically folks don't want to run their docker images _on_ circleci, they just want to build them & then deploy (push) them somewhere

what are you looking to do by running a docker image ?

& what other orbs are you looking to integrate with this orb ?

thanks !
