### ISSUE TITLE
Problem in "docker/install-docker-compose" script, problem with hash check

### ISSUE THREAD

**Issue by yonhir-d** [CircleCI-Public/docker-orb#51]
### Orb version

circleci/docker@0.5

### What happened

I intalled docker-compose with these steps:

```
steps:
            - checkout
            - docker/install-docker
            - docker/install-docker-compose
```

but in the script of install-docker-compose
the script failed to compare hash:

```
Latest stable version of docker-compose is 1.25.3
A different version of docker-compose is installed (docker-compose version 1.14.0, build c7bdf9e); removing it
sha256sum: standard input: no properly formatted SHA256 checksum lines found

Exited with code exit status 1
```

### Expected behavior

I researched and I think found the problem. Maybe the missing asterisk "*" at the start of the file name is causing the problem.

old file:
> 5df53b57bba0ad83af69f0f39c15f0316626302aba876954ea842892c875dd6a  docker-compose-Linux-x86_64

new file:

> 786f9390aa8d72bcf34a1757df71577b7d8b7cb915205f72f12b9ee3ca0e0cc6 *docker-compose-Linux-x86_64

**Comment by lokst** [comment]
@yonhir-d This should now be resolved in version `0.5.21` of the orb
