### ISSUE TITLE
403 rate limit exceeded error on docker/install-docker-compose 

### ISSUE THREAD

**Issue by agheorghe-careplanner** [CircleCI-Public/docker-orb#59]
### Orb version
0.5.0 / 1.0.0

### What happened
Occasionally our circle.ci jobs fail on the following step
```
      - docker/install-docker-compose:
          version: "1.21.0"
```
we are getting a 403 rate limit exceeded error (assuming this is triggered when attempting to download docker-compose from github)
```
A different version of docker-compose is installed (docker-compose version 1.14.0, build c7bdf9e); removing it
curl: (22) The requested URL returned error: 403 rate limit exceeded
``` 
### Expected behavior
Should install correctly and not hit a rate limit.

This has happened just a couple of times and a build retry has always worked, but was wondering is there is a way to use our organisation token/credentials to bypass this or if there is a different way to install a newer version of docker compose.

**Comment by lokst** [comment]
@agheorghe-careplanner This is something we will be looking into soon, thank you for your patience
