### ISSUE TITLE
Unable to use docker/publish in my orb

### ISSUE THREAD

**Issue by DrewTittle** [CircleCI-Public/docker-orb#63]
### Orb version

1.0.1

### What happened

When importing the docker-orb job 'publish' inside an orb I created I get an error:. 

╰─ circleci orb validate src/orb.yml

Error: Error calling job: 'docker/publish'
Missing required argument(s): image

Since I am importing the job for use in my orb I don't have a way to specify the parameter so I'm unable to validate with the cli or use the orb

### Expected behavior

I would like to be able to specify the docker-orb/publish job in my orb like so:

orbs:
  docker: circleci/docker@1.0.1
jobs:
  docker-publish: docker/publish

then in a workflow specify it like this

orbs:
  cicd-orb: namespace/cicd-orb@0.0.1

workflow:
  jobs:
    - cicd-orb/docker-publish

without errors related to the required image argument which can't be specified inside my orb (I believe...). If anyone knows of a workaround I'd be most appreciative!

**Comment by lokst** [comment]
Hi @DrewTittle , if I understand the issue correctly, I believe you should also expose an "image" parameter in your orb's job, so that you can pass it to `docker/publish`

**Comment by DrewTittle** [comment]
Hi @lokst 

I have tried specifying the image parameter where I import it into my orb. (note the YAML spacing is correct, github is just stripping it...)

jobs:
  docker-publish: docker/publish
    parameters:
      image:
        type: string

I get errors saying only a string can be used after the job import not a map.

╰─ circleci orb validate src/orb.yml              
Error: Unable to parse YAML
mapping values are not allowed here
 in 'string', line 25, column 15:
        parameters:

If there's some other way to accomplish this I couldn't find it documented.

**Comment by lokst** [comment]
@DrewTittle After looking over this again, I don't believe it's possible to embed another orb's job into your orb's job. Could you reference the orb's commands instead?

**Comment by gmemstr** [comment]
I agree with @lokst - because of the way jobs are defined and parameters are passed, jobs cannot be nested/aliased in other orbs. A custom job using the `docker/publish` command would be better suited.
