### ISSUE TITLE
I cannot omit $docker_tag_args when execute docker/build step

### ISSUE THREAD

**Issue by ChameleonTartu** [CircleCI-Public/docker-orb#64]
### Orb version
1.0.1

### What happened

I experienced this error in Circle CI.
```
#!/bin/bash -eo pipefail
docker_tag_args=""

IFS="," read -ra DOCKER_TAGS <<< "$CIRCLE_SHA1"
for tag in "${DOCKER_TAGS[@]}"; do
  docker_tag_args="$docker_tag_args -t customer.registy.io/my-image-name:${tag}"
done

docker build  \
  -f ./Dockerfile \
  $docker_tag_args \
  .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

Exited with code exit status 1
CircleCI received exit code 1
```

### Expected behavior

The issue is that I always have to use registry and tag. I would like to separate build and push functionality. In other words, in the current setup, I cannot run `docker build -f Dockerfile .` command to build an image.

**Comment by gmemstr** [comment]
Hi @ChameleonTartu - would you mind showing a bit more of the configuration that is going into this job? I suspect that you are using a Docker executor without the `setup_remote_docker` step: https://circleci.com/docs/2.0/building-docker-images/
