### ISSUE TITLE
dockerlint command bug (missing `-f` GNU option)

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [CircleCI-Public/docker-orb#79]
### Orb version

`1.0.5`

### What happened

using the `docker/dockerlint` Orb command causes the error `cannot open Dockerfile` , although the Dockerfile path is properly specified

### Expected behavior

That the Orb command uses properly the `-f` `dockerlint` option.

### Bugfix suggestion

Well look at the source code of the `docker/dockerlint` Orb Command at https://circleci.com/developer/orbs/orb/circleci/docker?version=1.5.0#commands-dockerlint :  yu willimmediately see that it does not make use of the `-f` option

**Comment by EricRibeiro** [comment]
Fix released in [v2.0.5](https://github.com/CircleCI-Public/docker-orb/releases/tag/v2.0.5).
