### ISSUE TITLE
Unable to specify `hadolint` image with `tag` parameter

### ISSUE THREAD

**Issue by alanjclark** [CircleCI-Public/docker-orb#80]
### Orb version

1.5.0

### What happened

We document how to specify an image for `hadolint` in the orb's documentation:

https://circleci.com/developer/orbs/orb/circleci/docker#executors-hadolint

It should be possible to to override the default `latest-debian` by specifying the image in the `tag` parameter. However, this does not appear to be functional.

Slack thread for reference:
https://circleci.slack.com/archives/CEX928FM3/p1620738198453300

### Expected behavior

The user should be able to override `latest-debian` by specifying an orb using the `tag` parameter.

**Comment by dserodio** [comment]
This has caused lots of our builds to begin to fail when hadolint was automatically updated due to hadolint/hadolint#606
