### ISSUE TITLE
new compose release breaks scripts

### ISSUE THREAD

**Issue by CrimsonGlory** [CircleCI-Public/docker-orb#94]
### Orb version
1.7.0 (latest)

### What happened
New version of docker compose (v2.0.0) have the files with "amd64" instead of "x86_64" in the name, so the curl returns 404 and compose fails to install.

```
curl: (22) The requested URL returned error: 404
```

**Comment by rafaeldriutti** [comment]
As a workaround you can set the docker compose version to a pre 2 release on your circleci yaml:

```
       - docker/install-docker-tools:
           docker-compose-version: 1.29.2
```

**Comment by CrimsonGlory** [comment]
Actually, looking at the V2 compose update, all repos were going to break anyway.

**Comment by JahangerGull** [comment]
> As a workaround you can set the docker compose version to a pre 2 release on your circleci yaml:
> 
> ```
>        - docker/install-docker-tools:
>            docker-compose-version: 1.29.2
> ```

It's not working circleci is raising an invalid configuration file errors.

**Comment by sidewaiise** [comment]
Also fixed this with
```
- docker/install-docker-compose:
    version: '1.29.2'
```

**Comment by felicianotech** [comment]
We're investigating.

**Comment by nqtrg** [comment]
@felicianotech 
The latest version of docker-compose at the time of reporting doesn't have versions for `x86_64`. That causes the script downloading the docker-compose binary to fail. So instead of getting the latest release, I modify the script to get the latest release containing the version for `x86_64`. What do you think? 
```
DOCKER_COMPOSE_VERSION=$(curl -s --fail --retry 3 "https://github.com/docker/compose/releases/" | grep -Eoi '<a [^>]+>' | grep -Eo 'href="[^\"]+"'| grep x86_64 | head -1 | awk -F'/' '{print $6}')
```

**Comment by EricRibeiro** [comment]
I'm closing this issue since this hasn't been a problem as of docker-compose version 2.5.0.

Should it occur again, we can follow @nguqtruong's suggestion.
